// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for RabbitMqApiCallFunction
 */
export interface RabbitMqApiCallFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/rabbitmq/custom-resource/handler/rabbit-mq-api-call.
 */
export class RabbitMqApiCallFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: RabbitMqApiCallFunctionProps) {
    super(scope, id, {
      description: 'src/rabbitmq/custom-resource/handler/rabbit-mq-api-call.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs18.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../../assets/rabbitmq/custom-resource/handler/rabbit-mq-api-call.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}