// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { determineLatestNodeRuntime } from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for EsmDeleterIsCompleteFunction
 */
export interface EsmDeleterIsCompleteFunctionProps extends lambda.FunctionOptions {
  /**
   * The Lambda runtime to use.
   * @default - Latest Node.js runtime available in the deployment region
   */
  readonly runtime?: lambda.Runtime;
}

/**
 * An AWS Lambda function which executes src/mq-esm/esm-deleter.is-complete.
 */
export class EsmDeleterIsCompleteFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: EsmDeleterIsCompleteFunctionProps) {
    super(scope, id, {
      description: 'src/mq-esm/esm-deleter.is-complete.lambda.ts',
      ...props,
      runtime: props?.runtime ?? determineLatestNodeRuntime(scope),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/mq-esm/esm-deleter.is-complete.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}